### ISSUE TITLE
WordPress Plugin/Module

### ISSUE THREAD

**Issue by onovotny** [Microsoft/AppInsights-PHP#1]
Can this be packaged up as a WordPress Plugin/Module so we can instrument the PHP portion of a WordPress site? We can already add the web page portion via script headers, but that doesn't handle server exceptions, page response time, etc.

**Comment by JakubOleksy-Microsoft** [comment]
Thanks for the request. I'm actually working on this exact thing.

**Comment by onovotny** [comment]
:+1:

**Comment by JakubOleksy-Microsoft** [comment]
I've moved to using GitHub for the WordPress plugin development and the version there integrates (starts to) the PHP SDK. I will publish it to WordPress soon, I need to work through some issues as I need to redistribute the dependencies there. 

https://github.com/Microsoft/AppInsights-WordPress

**Comment by JakubOleksy-Microsoft** [comment]
In the meantime, you can install manually by pulling in the composer dependencies yourself.
