### ISSUE TITLE
Not possible to link an exception (or anything) to a request

### ISSUE THREAD

**Issue by gardnerjr** [Microsoft/AppInsights-PHP#3]
The backend links requests and other telemetry calls during that request by using the request's id as the context.id in other calls.

but right now, the request id isn't settable because it gets created only when the request is sent.  you can properly set the context.id for everything, but not using the value from request.

It appears there should be some concept of `BeginRequest` on `TelemetryClient` which you can call at the beginning of a request, get the id from that, use it to set context.id, and then call `EndRequest` when the request is completed?

**Comment by JakubOleksy-Microsoft** [comment]
With the latest merge this issue is not resolved. Thanks!
